//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationtes2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int IdProduct { get; set; }
        public string ProductName { get; set; }
        public int IdVendor { get; set; }
        public int Stok { get; set; }
        public int StatusProduct { get; set; }
    
        public virtual tbl_Vendor tbl_Vendor { get; set; }
    }
}
